dt3 = new Date()
console.log(dt3.getDate()  + " this is getDate") 
console.log(dt3.getFullYear() +" this is getFullYear")
console.log(dt3.getMonth() + " this is getMonth")
console.log(dt3.getDay() + " this is getDay")
console.log(dt3.getHours() + " this is getHours")
console.log(dt3.getMinutes() + " this is getMinutes")
console.log(dt3.getSeconds() + " this is getSeconds")
console.log(dt3.getMilliseconds() + " this is getMilliseconds")
console.log(dt3.getTime() + " this is getTime")
console.log(dt3.getTimezoneOffset() + " this is getTimezoneOffset")
console.log(dt3.getUTCDate() + " this is getUTCDate")
console.log(dt3.getUTCFullYear() + " this is getUTCFullYear")
console.log(dt3.getUTCMonth() + " this is getUTCMonth")
console.log(dt3.getUTCDay() + " this is getUTCDay")
console.log(dt3.getUTCHours() + " this is getUTCHours")
console.log(dt3.getUTCMinutes() + " this is getUTCMinutes")
console.log(dt3.getUTCSeconds() + " this is getUTCSeconds")
console.log(dt3.getUTCMilliseconds() + " this is getUTCMilliseconds")